# /home/angel/helix-hub/docker-compose.yml
services:
  traefik:
    image: traefik:v2.10
    command:
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.docker=false
      - --entryPoints.websecure.address=:8443
      - --api.dashboard=true
      - --log.level=INFO
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/certs:/certs:ro
    networks:
      - helix-net
    restart: unless-stopped

  helix-core:
    build: ./helix-core
    image: helix/helix-core:dev
    environment:
      - FLASK_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - DATABASE_URL=postgresql://helix:helixpass@postgres:5432/helix
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key}
      - SFTP_HOST=sftp-demo
      - SFTP_PORT=22
      - SFTP_USER=bank
      - SFTP_PASS=bankpassword
      - SFTP_REMOTE_DIR=/incoming
    depends_on:
      - postgres
      - sftp-demo
    ports:
      - "5000:5000"
    volumes:
      - ./helix-core/data:/app/data
    networks:
      - helix-net
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: helix
      POSTGRES_USER: helix
      POSTGRES_PASSWORD: helixpass
    volumes:
      - helix_db_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - helix-net
    restart: unless-stopped

  sftp-demo:
    image: atmoz/sftp:latest
    command: bank:bankpassword:1001
    volumes:
      - ./sftp/incoming:/home/bank/incoming
    ports:
      - "2222:22"
    networks:
      - helix-net
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:1.19.4
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Europe/Zurich
    volumes:
      - n8n_data:/home/node/.n8n
      - ./podcast-studio:/podcast-studio:ro
    networks:
      - helix-net

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - helix-net

  # Web-based file manager for SFTP access
  filebrowser:
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./sftp/incoming:/srv/sftp:ro
      - ./helix-core/data:/srv/data
      - filebrowser_data:/database
    environment:
      - FB_DATABASE=/database/database.db
      - FB_USERNAME=admin
      - FB_PASSWORD=admin
    networks:
      - helix-net

  # HashiCorp Vault - Secret Management Engine
  vault:
    image: hashicorp/vault:1.15.2
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - ./vault/config:/vault/config:ro
      - ./vault/auto-unseal:/vault/auto-unseal:ro
    networks:
      - helix-net
    command: ["vault", "server", "-dev"]

  # Keycloak - Authentication Engine (Threading Through to Vault!)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak_db
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_secure_pass
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_PROXY=edge
      - KC_HOSTNAME=keycloak.helix.local
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HEALTH_ENABLED=true
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realms:/opt/keycloak/data/import:ro
    networks:
      - helix-net
    depends_on:
      - postgres
      - vault
    command: ["start-dev", "--import-realm"]

volumes:
  helix_db_data:
  n8n_data:
  ollama_data:
  filebrowser_data:
  vault_data:
  keycloak_data:

networks:
  helix-net:
    driver: bridge
