# docker-compose.yml for Helix MVP
# C:\windows\System32\drivers\etc hosts 127.0.0.1 helix.local
services:
  traefik:
    image: traefik:v2.10
    command:
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.docker=false
      - --entryPoints.websecure.address=:8443
      - --api.dashboard=true
      - --log.level=INFO
      - --certificatesresolvers.mktls.acme.tlschallenge=false
    ports:
      - "8443:8443" # HTTPS for helix.local
      - "8080:8080" # Traefik dashboard (protect in prod)
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/certs:/certs:ro
    restart: unless-stopped

  helix-core:
    build: ./helix-core
    image: helix/helix-core:dev
    environment:
      - FLASK_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - DATABASE_URL=postgresql://helix:helixpass@postgres:5432/helix
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key}
      - SFTP_HOST=sftp-demo
      - SFTP_PORT=22
      - SFTP_USER=bank
      - SFTP_PASS=bankpassword
      - SFTP_REMOTE_DIR=/incoming
    depends_on:
      - postgres
      - sftp-demo
    ports:
      - "5000:5000"  # Expose Flask app directly for development
    volumes:
      - ./helix-core/data:/app/data
    networks:
      - helix-net
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: helix
      POSTGRES_USER: helix
      POSTGRES_PASSWORD: helixpass
    volumes:
      - helix_db_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - helix-net
    restart: unless-stopped

  sftp-demo:
    image: atmoz/sftp:latest
    command: bank:bankpassword:1001
    volumes:
      - ./sftp/incoming:/home/bank/incoming
    ports:
      - "2222:22"
    networks:
      - helix-net
    restart: unless-stopped

volumes:
  helix_db_data:

networks:
  helix-net:
    driver: bridge