http:
  routers:
# Keycloak authentication service
    keycloak-router:
      rule: "Host(`keycloak.helix.local`)"
      entryPoints:
        - websecure
      service: keycloak-service
      tls: {}
# n8n
    n8n-router:
      rule: "Host(`n8n.helix.local`)"
      entryPoints:
        - websecure
      service: n8n-service
      tls: {}
# vault router
    vault:
      rule: "Host(`vault.helix.local`)"
      entryPoints:
        - "websecure"
      service: "vault-service"
      tls: {}
# Main Helix Core application
    helix-router:
      rule: "Host(`helix.local`)"
      entryPoints:
        - websecure
      service: helix-service
      tls: {}
# Traefik Dashboard
    traefik-router:
      rule: "Host(`traefik.helix.local`)"
      entryPoints:
        - websecure
      service: api@internal
      tls: {}
# Ollama API
    ollama-router:
      rule: "Host(`ollama.helix.local`)"
      entryPoints:
        - websecure
      service: ollama-service
      tls: {}
# FileBrowser - Web-based file manager
    files-router:
      rule: "Host(`files.helix.local`)"
      entryPoints:
        - websecure
      service: files-service
      tls: {}
# SFTP (legacy - now using FileBrowser)
    sftp-router:
      rule: "Host(`sftp.helix.local`)"
      entryPoints:
        - websecure
      service: files-service
      tls: {}

  services:
    helix-service:
      loadBalancer:
        servers:
          - url: "http://helix-core:5000"
    ollama-service:
      loadBalancer:
        servers:
          - url: "http://ollama:11434"
    files-service:
      loadBalancer:
        servers:
          - url: "http://filebrowser:80"
    sftp-service:
      loadBalancer:
        servers:
          - url: "http://sftp-demo:22"
    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://keycloak:8080"
    n8n-service:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"
    vault-service:
      loadBalancer:
        servers:
          - url: "http://vault:8200"
    traefik-service:
      loadBalancer:
        servers:
          - url: "http://traefik:8080"
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: /certs/helix.local.pem
      keyFile: /certs/helix.local-key.pem
  options:
    mkcert-tls:
      minVersion: "VersionTLS12"
      clientAuth:
        caFiles:
          - /certs/rootCA.pem
        clientAuthType: RequestClientCert