http:
  routers:
    # Main Helix Core application
    helix-router:
      rule: "Host(`helix.local`)"
      entryPoints:
        - websecure
      service: helix-service
      tls: {}
    
    # Traefik Dashboard
    traefik-router:
      rule: "Host(`traefik.helix.local`)"
      entryPoints:
        - websecure
      service: api@internal
      tls: {}
    
    # Ollama API
    ollama-router:
      rule: "Host(`ollama.helix.local`)"
      entryPoints:
        - websecure
      service: ollama-service
      tls: {}
    
    # SFTP (future web interface)
    sftp-router:
      rule: "Host(`sftp.helix.local`)"
      entryPoints:
        - websecure
      service: sftp-service
      tls: {}

  services:
    helix-service:
      loadBalancer:
        servers:
          - url: "http://helix-core:5000"
    
    ollama-service:
      loadBalancer:
        servers:
          - url: "http://ollama:11434"
    
    sftp-service:
      loadBalancer:
        servers:
          - url: "http://sftp-demo:22"

  middlewares:
    jwt-auth:
      forwardAuth:
        address: "http://helix-core:5000/auth/validate"
        trustForwardHeader: true
        authResponseHeaders:
          - "Authorization"
        authRequestHeaders:
          - "Authorization"

tls:
  certificates:
    - certFile: /certs/helix.local.pem
      keyFile: /certs/helix.local-key.pem
  options:
    mkcert-tls:
      minVersion: "VersionTLS12"
      clientAuth:
        caFiles:
          - /certs/rootCA.pem
        clientAuthType: RequestClientCert